export const carDb = [
  {model: "CX-5", category: "suv", make: "Mazda", year: "2019", price: "23000", image: "suv"},
  {model: "Civic", category: "hatchback", make: "Honda", year: "2020", price: "24000", image: "hatchback"},
  {model: "Camry", category: "sedan", make: "Toyota", year: "2019", price: "25000", image: "sedan"},
  {model: "Sienna", category: "van", make: "Toyota", year: "2020", price: "28000", image: "van"},
  {model: "Miata", category: "convertible", make: "Mazda", year: "2017", price: "23000", image: "convertible"},
  {model: "F-150", category: "utility", make: "Ford", year: "2020", price: "40000", image: "utility"},
  {model: "Rogue", category: "suv", make: "Nissan", year: "2017", price: "18000", image: "suv-1"},
  {model: "Golf GTI", category: "hatchback", make: "Volkswagen", year: "2018", price: "27000", image: "hatchback-1"},
  {model: "Accord", category: "sedan", make: "Honda", year: "2022", price: "32000", image: "sedan-1"},
  {model: "Odyssey", category: "van", make: "Honda", year: "2021", price: "33000", image: "van-1"},
  {model: "Z4", category: "convertible", make: "BMW", year: "2021", price: "54000", image: "convertible-1"},
  {model: "Silverado", category: "utility", make: "Chevrolet", year: "2019", price: "38000", image: "utility-1"},
  {model: "Highlander", category: "suv", make: "Toyota", year: "2022", price: "36000", image: "suv-2"},
  {model: "i30 N", category: "hatchback", make: "Hyundai", year: "2021", price: "32000", image: "hatchback-2"},
  {model: "Altima", category: "sedan", make: "Nissan", year: "2018", price: "19000", image: "sedan-2"},
  {model: "Sprinter", category: "van", make: "Mercedes-Benz", year: "2019", price: "45000", image: "van-2"},
  {model: "Mustang", category: "convertible", make: "Ford", year: "2018", price: "32000", image: "convertible-2"},
  {model: "Ram 1500", category: "utility", make: "Dodge", year: "2022", price: "43000", image: "utility-2"},
  {model: "SUV", category: "suv", make: "Subaru", year: "2022", price:"32000", image: "suv-3"},
  {model: "HATCHBACK", category: "hatchback", make: "Volkswagen", year: "2021", price:"54000", image: "hatchback-3"},
  {model: "SEDAN", category: "sedan", make: "Audi", year: "2020",price:"22000", image: "sedan-3"},
  {model: "VAN", category: "van", make: "Toyota", year: "2019",  price:"", image: "van-3"},
  {model: "CONVERTIBLE", category: "convertible", make: "Porsche", year: "2018", price:"20000", image: "convertible-3"},
  {model: "UTILITY", category: "utility", make: "GMC", year: "2017", price:"18000", image: "utility-3"},
  {model: "SUV", category: "suv", make: "Jeep", year: "2022", price:"25400", image: "suv-4"},
  {model: "HATCHBACK", category: "hatchback", make: "Fiat", year: "2021", price:"27500", image: "hatchback-4"},
  {model: "SEDAN", category: "sedan", make: "Volvo", year: "2020",  price:"23300",image: "sedan-4"},
  {model: "VAN", category: "van", make: "Honda", year: "2019", price:"35400", image: "van-4"},
  {model: "CONVERTIBLE", category: "convertible", make: "Lamborghini", year: "2018", price:"31500", image: "convertible-4"},
  {model: "UTILITY", category: "utility", make:"Kia", year:"2020", price:"19000", image: "utility-4"},
  {model: "CX-5", category: "suv", make: "Mazda", year: "2019", price: "23000", image: "suv"},
  {model: "Civic", category: "hatchback", make: "Honda", year: "2020", price: "24000", image: "hatchback"},
  {model: "Camry", category: "sedan", make: "Toyota", year: "2019", price: "25000", image: "sedan"},
  {model: "Sienna", category: "van", make: "Toyota", year: "2020", price: "28000", image: "van"},
  {model: "Miata", category: "convertible", make: "Mazda", year: "2017", price: "23000", image: "convertible"},
  {model: "F-150", category: "utility", make: "Ford", year: "2020", price: "40000", image: "utility"},
  ]