export const CARS =  [
  {model: "SUV", category: "suv", make: "Toyota", year: "2022", image: "suv"},
  {model: "HATCHBACK", category: "hatchback", make: "Honda", year: "2021", image: "hatchback"},
  {model: "SEDAN", category: "sedan", make: "Nissan", year: "2020", image: "sedan"},
  {model: "VAN", category: "van", make: "Chrysler", year: "2019", image: "van"},
  {model: "CONVERTIBLE", category: "convertible", make: "BMW", year: "2018", image: "convertible"},
  {model: "UTILITY", category: "utility", make: "Ford", year: "2017", image: "utility"},
  {model: "SUV", category: "suv", make: "Mitsubishi", year: "2022", image: "suv"},
  {model: "HATCHBACK", category: "hatchback", make: "Hyundai", year: "2021", image: "hatchback"},
  {model: "SEDAN", category: "sedan", make: "Kia", year: "2020", image: "sedan"},
  {model: "VAN", category: "van", make: "Dodge", year: "2019", image: "van"},
  {model: "CONVERTIBLE", category: "convertible", make: "Mercedes-Benz", year: "2018", image: "convertible"},
  {model: "UTILITY", category: "utility", make: "Chevrolet", year: "2017", image: "utility"},
  {model: "SUV", category: "suv", make: "Subaru", year: "2022", image: "suv"},
  {model: "HATCHBACK", category: "hatchback", make: "Volkswagen", year: "2021", image: "hatchback"},
  {model: "SEDAN", category: "sedan", make: "Audi", year: "2020", image: "sedan"},
  {model: "VAN", category: "van", make: "Toyota", year: "2019", image: "van"},
  {model: "CONVERTIBLE", category: "convertible", make: "Porsche", year: "2018", image: "convertible"},
  {model: "UTILITY", category: "utility", make: "GMC", year: "2017", image: "utility"},
  {model: "SUV", category: "suv", make: "Jeep", year: "2022", image: "suv"},
  {model: "HATCHBACK", category: "hatchback", make: "Fiat", year: "2021", image: "hatchback"},
  {model: "SEDAN", category: "sedan", make: "Volvo", year: "2020", image: "sedan"},
  {model: "VAN", category: "van", make: "Honda", year: "2019", image: "van"},
  {model: "CONVERTIBLE", category: "convertible", make: "Lamborghini", year: "2018", image: "convertible"},
  {model: "UTILITY", category: "utility", make:"Kia", year:"2020", image: "utility"}
]